config/routes.rb
Rails.application.routes.draw do
  scope :api, defaults: {format: :json} do
    resources :foos
    resources :bars
    resources :cities
    resources :states
  end
  
  get '/ui' => 'ui#index'
  get '/ui#' => 'ui#index'
  root "ui#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bar.rb
class Bar
  include Mongoid::Document
  include Mongoid::Timestamps
  field :name, type: String
end

app/models/city.rb
class City < ApplicationRecord
end

app/models/foo.rb
class Foo < ApplicationRecord
end

app/models/state.rb
class State
  include Mongoid::Document
  include Mongoid::Timestamps
  field :name, type: String
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ActionController::ImplicitRender
  protect_from_forgery with: :exception
end

app/controllers/bars_controller.rb
class BarsController < ApplicationController
  before_action :set_bar, only: [:show, :edit, :update, :destroy]

  def index
    @bars = Bar.all
  end

  def show
  end


  def create
    @bar = Bar.new(bar_params)

    if @bar.save
        render :show, status: :created, location: @bar 
    else
        render json: @bar.errors, status: :unprocessable_entity
    end
  end


  def update
    @bar = Bar.find(params[:id]) 

    if @bar.update(bar_params)
        head :no_content
    else
        render json: @bar.errors, status: :unprocessable_entity
    end
  end

  def destroy
    @bar.destroy
    head :no_content 
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bar
      @bar = Bar.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bar_params
      params.require(:bar).permit(:name)
    end
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  before_action :set_city, only: [:show, :edit, :update, :destroy]

  def index
    @cities = City.all
  end

    
  def show
  end

     
  def create
    @city = City.new(city_params)

    if @city.save
        render :show, status: :created, location: @city 
    else
        render json: @city.errors, status: :unprocessable_entity 
    end
  end

    
  def update
    @city = City.find(params[:id])
      
    if @city.update(city_params)
        head :no_content
    else
        render json: @city.errors, status: :unprocessable_entity 
    end
  end

    
  def destroy
    @city.destroy
    head :no_content
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_city
      @city = City.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def city_params
      params.require(:city).permit(:id, :name)
    end
end

app/controllers/foos_controller.rb
class FoosController < ApplicationController
  before_action :set_foo, only: [:show, :edit, :update, :destroy]

  def index
    @foos = Foo.all
  end

    
  def show
  end


  def create
    @foo = Foo.new(foo_params)
      
    if @foo.save
        render :show, status: :created, location: @foo
    else
        render json: @foo.errors, status: :unprocessable_entity
    end
  end


  def update
    @foo = Foo.find(params[:id])  
      
    if @foo.update(foo_params)
        head :no_content
    else
        render json: @foo.errors, status: :unprocessable_entity
    end
  end


  def destroy
    @foo.destroy
    head :no_content
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_foo
      @foo = Foo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def foo_params
      params.require(:foo).permit(:name)
    end
end

app/controllers/states_controller.rb
class StatesController < ApplicationController
  before_action :set_state, only: [:show, :edit, :update, :destroy]

  # GET /states
  # GET /states.json
  def index
    @states = State.all
  end

  # GET /states/1
  # GET /states/1.json
  def show
  end

  # GET /states/new
  def new
    @state = State.new
  end

  # GET /states/1/edit
  def edit
  end

  # POST /states
  # POST /states.json
  def create
    @state = State.new(state_params)

    respond_to do |format|
      if @state.save
        format.html { redirect_to @state, notice: 'State was successfully created.' }
        format.json { render :show, status: :created, location: @state }
      else
        format.html { render :new }
        format.json { render json: @state.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /states/1
  # PATCH/PUT /states/1.json
  def update
    respond_to do |format|
      if @state.update(state_params)
        format.html { redirect_to @state, notice: 'State was successfully updated.' }
        format.json { render :show, status: :ok, location: @state }
      else
        format.html { render :edit }
        format.json { render json: @state.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /states/1
  # DELETE /states/1.json
  def destroy
    @state.destroy
    respond_to do |format|
      format.html { redirect_to states_url, notice: 'State was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_state
      @state = State.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def state_params
      params.require(:state).permit(:name)
    end
end

app/controllers/ui_controller.rb
class UiController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bars_helper.rb
module BarsHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/foos_helper.rb
module FoosHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/helpers/ui_helper.rb
module UiHelper
end

app/views/bars/_form.html.erb
<%= form_for(bar) do |f| %>
  <% if bar.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bar.errors.count, "error") %> prohibited this bar from being saved:</h2>

      <ul>
      <% bar.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bars/edit.html.erb
<h1>Editing Bar</h1>

<%= render 'form', bar: @bar %>

<%= link_to 'Show', @bar %> |
<%= link_to 'Back', bars_path %>

app/views/bars/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bars</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bars.each do |bar| %>
      <tr>
        <td><%= bar.name %></td>
        <td><%= link_to 'Show', bar %></td>
        <td><%= link_to 'Edit', edit_bar_path(bar) %></td>
        <td><%= link_to 'Destroy', bar, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bar', new_bar_path %>

app/views/bars/new.html.erb
<h1>New Bar</h1>

<%= render 'form', bar: @bar %>

<%= link_to 'Back', bars_path %>

app/views/bars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @bar.name %>
</p>

<%= link_to 'Edit', edit_bar_path(@bar) %> |
<%= link_to 'Back', bars_path %>

app/views/cities/_form.html.erb
<%= form_for(city) do |f| %>
  <% if city.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(city.errors.count, "error") %> prohibited this city from being saved:</h2>

      <ul>
      <% city.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %>
    <%= f.number_field :id %>
  </div>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cities/edit.html.erb
<h1>Editing City</h1>

<%= render 'form', city: @city %>

<%= link_to 'Show', @city %> |
<%= link_to 'Back', cities_path %>

app/views/cities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cities</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cities.each do |city| %>
      <tr>
        <td><%= city.id %></td>
        <td><%= city.name %></td>
        <td><%= link_to 'Show', city %></td>
        <td><%= link_to 'Edit', edit_city_path(city) %></td>
        <td><%= link_to 'Destroy', city, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New City', new_city_path %>

app/views/cities/new.html.erb
<h1>New City</h1>

<%= render 'form', city: @city %>

<%= link_to 'Back', cities_path %>

app/views/cities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id:</strong>
  <%= @city.id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @city.name %>
</p>

<%= link_to 'Edit', edit_city_path(@city) %> |
<%= link_to 'Back', cities_path %>

app/views/foos/_form.html.erb
<%= form_for(foo) do |f| %>
  <% if foo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(foo.errors.count, "error") %> prohibited this foo from being saved:</h2>

      <ul>
      <% foo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/foos/edit.html.erb
<h1>Editing Foo</h1>

<%= render 'form', foo: @foo %>

<%= link_to 'Show', @foo %> |
<%= link_to 'Back', foos_path %>

app/views/foos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Foos</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @foos.each do |foo| %>
      <tr>
        <td><%= foo.name %></td>
        <td><%= link_to 'Show', foo %></td>
        <td><%= link_to 'Edit', edit_foo_path(foo) %></td>
        <td><%= link_to 'Destroy', foo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Foo', new_foo_path %>

app/views/foos/new.html.erb
<h1>New Foo</h1>

<%= render 'form', foo: @foo %>

<%= link_to 'Back', foos_path %>

app/views/foos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @foo.name %>
</p>

<%= link_to 'Edit', edit_foo_path(@foo) %> |
<%= link_to 'Back', foos_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Demoapp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/states/_form.html.erb
<%= form_for(state) do |f| %>
  <% if state.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(state.errors.count, "error") %> prohibited this state from being saved:</h2>

      <ul>
      <% state.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/states/edit.html.erb
<h1>Editing State</h1>

<%= render 'form', state: @state %>

<%= link_to 'Show', @state %> |
<%= link_to 'Back', states_path %>

app/views/states/index.html.erb
<p id="notice"><%= notice %></p>

<h1>States</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @states.each do |state| %>
      <tr>
        <td><%= state.name %></td>
        <td><%= link_to 'Show', state %></td>
        <td><%= link_to 'Edit', edit_state_path(state) %></td>
        <td><%= link_to 'Destroy', state, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New State', new_state_path %>

app/views/states/new.html.erb
<h1>New State</h1>

<%= render 'form', state: @state %>

<%= link_to 'Back', states_path %>

app/views/states/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @state.name %>
</p>

<%= link_to 'Edit', edit_state_path(@state) %> |
<%= link_to 'Back', states_path %>

app/views/ui/index.html.erb
Capstone Site Under Construction -- check back soon